config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :cart_items, only: [:index, :show, :destroy] do
        collection do
          post :upsert
          delete :reset
        end
      end
      resources :products, only: [:index, :create, :update, :destroy]
    end
  end

  get "cart", to: "cart#show"

  resources :products

  root "products#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  class << self
    def find_with_response(id, includes: nil)
      find_wrapper(id, includes) { includes(includes).find(id) }
    end

    def find_wrapper(id, _includes)
      Response.success(yield)
    rescue ActiveRecord::RecordNotFound => _e
      Response.failure("Cannot find #{name} with id: #{id}")
    end
  end

  def save_with_response(**args)
    assign_attributes(args)
    if save
      Response.success(self)
    else
      Response.failure(errors.full_messages.to_sentence)
    end
  end

  def update_attributes_with_response(args)
    if errors.details.empty? && update(args)
      Response.success(self)
    else
      Response.failure(errors.full_messages.to_sentence)
    end
  end

  def destroy_with_response
    if destroy
      Response.success(self)
    else
      Response.failure(errors.full_messages.to_sentence)
    end
  end

  private

  def response_success
    Response.success(self)
  end

  def response_failure
    Response.failure(errors.full_messages.to_sentence)
  end
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_many :cart_items, dependent: :delete_all
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
# frozen_string_literal: true

class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  with_options presence: true do
    validates :quantity, numericality: { greater_than: 0 }
    validates :total_price
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :cart_items, dependent: :delete_all
  has_one_attached :image

  with_options presence: true do
    validates :name, :vendor, :price
    validates :price, numericality: { greater_than: 0 }
  end

  before_validation :convert_price_to_cents
  after_update_commit :update_cart_items_price

  def product_image
    return unless image.attached?

    Rails.application.routes.url_helpers.rails_representation_url(
      image.variant(resize_to_fit: [150, 250], format: :webp),
      only_path: true
    )
  end

  def price_in_dollars
    price.present? ? price.to_d / 100 : nil
  end

  def price_in_dollars=(dollar_amount)
    self.price = (dollar_amount.to_d * 100).round(0) if dollar_amount.present?
  end

  private

  def convert_price_to_cents
    return if price.nil? || price.to_i > 100

    self.price = (price.to_d * 100).round(0)
  end

  def update_cart_items_price
    cart_items.each { _1.update(total_price: price * _1.quantity) }
  end
end

app/controllers/api/v1/cart_items_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class CartItemsController < ApplicationController
      def index
        cart_items = CartItem.eager_load(:product).where(cart_id: @cart.id).order(created_at: :asc)

        render json: cart_items,
               each_serializer: ::V1::CartItemSerializer,
               status: :ok
      end

      def show
        render json: cart_item, serializer: ::V1::CartItemSerializer
      end

      def upsert
        response = ShoppingCart::CartItems::Upsert.new(cart: @cart,
                                                       product_id: params[:product_id],
                                                       quantity: params[:quantity]).call

        if response.success?
          render json: {
            cart_item: ::V1::CartItemSerializer.new(response.value).serializable_hash,
            message: "Your cart has been updated!",
          }, status: :ok
        else
          render json: { errors: response.value }, status: :unprocessable_entity
        end
      end

      def destroy
        response = ShoppingCart::CartItems::Destroy.new(cart: @cart, cart_item_id: params[:id]).call

        if response.success?
          render json: { message: "The product has been removed from your cart!" }, status: :ok
        else
          render json: { errors: response.value, status: :unprocessable_entity }
        end
      end

      def reset
        response = ShoppingCart::Reset.new(cart: @cart).call

        if response.success?
          render json: { message: "Your cart has been emptied!" }, status: :ok
        else
          render json: { errors: response.value, status: :unprocessable_entity }
        end
      end

      private

      def cart_item
        @cart_item ||= CartItem.find_by(id: params[:id])
      end
    end
  end
end

app/controllers/api/v1/products_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ProductsController < ApplicationController
      def index
        products = Product.order(created_at: :desc)

        render json: products,
               each_serializer: ::V1::ProductSerializer,
               root: "products",
               status: :ok
      end

      def destroy
        response = product.destroy_with_response

        if response.success?
          render json: { message: "Product was successfully removed!" }, status: :ok
        else
          render json: { errors: response.value }, status: :unprocessable_entity
        end
      end

      private

      def product
        @product ||= Product.find(params[:id])
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :initialize_cart

  private

  def initialize_cart # rubocop:disable Metrics/AbcSize
    if Rails.env.test? && request.headers["X-Cart-ID"].present?
      @cart = Cart.find_by(id: request.headers["X-Cart-ID"])
    else
      @cart ||= Cart.find_by(id: session[:cart_id]) || Cart.create
      session[:cart_id] = @cart.id
    end
  end
end

app/controllers/cart_controller.rb
# frozen_string_literal: true

class CartController < ApplicationController
  # rubocop:disable Lint/EmptyMethod
  def show
  end
  # rubocop:enable Lint/EmptyMethod
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  # rubocop:disable Lint/EmptyMethod
  def index
  end
  # rubocop:enable Lint/EmptyMethod

  def new
    @product = Product.new
  end

  def edit
    product
  end

  def create
    @product = Product.find_or_initialize_by(product_attributes.except(:image, :price_in_dollars))
    %i(price_in_dollars image).each do |attribute|
      @product.public_send("#{attribute}=", product_attributes[attribute])
    end

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if product.update(product_attributes)
        format.html { redirect_to products_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      format.html { redirect_to products_path } if product.destroy
    end
  end

  private

  def product
    @product ||= Product.find(params[:id])
  end

  def product_attributes
    params.require(:product).permit(:name, :vendor, :image, :price_in_dollars)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def cents_to_amount(amount)
    return if amount.nil?

    format("%.2f", amount.to_d / 100)
  end
end

app/helpers/react_helper.rb
# frozen_string_literal: true

module ReactHelper
  def asset_path_helper(asset)
    ActionController::Base.helpers.asset_path(asset)
  end
end

app/views/cart/show.html.erb
<%= react_component "Cart", props: { boxIconPath: asset_path("box-icon.png") } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingCart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
    <div class="container-fluid align-items-center">
      <%= react_component "FlashAlerts" %>
      <div class="row">
        <div class="col-6 mt-3">
          <%= link_to products_path do %>
            <%= image_tag "loadar.png", width: 200 %>
          <% end %>
        </div>
      </div>
      <hr>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: @product) do |form| %>
  <% %i(vendor name price).each do |name| %>
    <%= render "shared/text_field", form:, name:, type: "text", errors: @product.errors[name] %>
  <% end %>

  <div data-controller="image-preview">
    <%= form.file_field :image, class: "form-control", accept: "image/*", data: { image_preview_target: "input" } %>
    
    <img
      id="image-preview"
      src="<%= url_for(@product.image) if @product.image.attached? %>"
      class="img-thumbnail"
      style="max-width: 200px; display: <%= @product.image.attached? ? 'block' : 'none' %>;"
      data-image-preview-target="preview"\
    >
  </div>

  <div class="pt-2">
    <%= form.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Cancel", products_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="row align-items-center justify-content-center mb-2">
  <div class="col-1 text-center">
    <%= link_to edit_product_path(product.id), class: "btn btn-sm btn-light ml-1", title: "Edit product" do %>
      <%= fa_icon "pencil" %>
    <% end %>
    <%= link_to product, class: "btn btn-sm btn-light ml-1", title: "Remove product", data: { confirm: "Do you really want to remove this product?" }, method: :delete do %>
      <%= fa_icon "trash" %>
    <% end %>
  </div>
  <div class="col-2">
    <%= image_tag product.image.variant(resize_to_fit: [150, 250]) %>
  </div>
  <div class="col-2">
    <%= product.name %>
  </div>
  <div class="col-1">
    <%= number_to_currency cents_to_amount(product.price), unit: "€" %>
  </div>
  <div class="col-2">
    <%= form_with(url: api_v1_cart_items_upsert_path, remote: true) do |f| %>
      <%= f.hidden_field :product_id, value: product.id %>
      <%= f.hidden_field :quantity, value: 1, class: "form-control mr-2" %>
      <%= f.submit "Add to cart", class: "btn btn-light" %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<div class="container-fluid mt-4 align-items-center">
  <div class="row">
    <div class="col-6">
      <h1>Edit product: <%= @product.name %></h1>
    </div>
    <div class="col-6">
      <%= button_to product_path(@product), method: :delete, class: "btn btn-danger mt-2 float-end" do %>
        <%= fa_icon "trash" %>
      <%end %>
    </div>
  </div>
  <hr/>
  
  <div class="container mb-5">
    <div class="row">
      <div class="col-6">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<%= react_component "ProductList", props: { cartItems: @cart.cart_items } %>

app/views/products/new.html.erb
<div class="container-fluid mt-4 align-items-center">
  <div class="row">
    <div class="col-12">
      <h1>New product</h1>
    </div>
  </div>
  <hr/>

  <div class="container mb-5">
    <div class="row">
      <div class="col-12">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_text_field.html.erb
<div class="mb-3">
  <%= form.label name, class: "form-label" %>
  <% if name.to_s.include?("price") %>
    <%= form.text_field :price_in_dollars,
        class: "form-control",
        value: form.object.send(name) ? cents_to_amount(form.object.send(name)) : nil,
        placeholder: "Price in dollars" 
    %>
  <% else %>
    <%= form.text_field name, class: "form-control", placeholder: name %>
  <% end %>
  <% if errors.any? %>
    <p style="color: red"><%= errors.join(", ") %></p>
  <% end %>
</div>